version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: fitness_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: fitness_user
      POSTGRES_PASSWORD: fitness_pass_2024
      POSTGRES_DB: fitness_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fitness_user -d fitness_system"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: fitness_server
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: development
      PORT: 5000
      DATABASE_URL: postgresql://fitness_user:fitness_pass_2024@postgres:5432/fitness_system
      JWT_SECRET: your_super_secret_jwt_key_change_in_production
      JWT_EXPIRE: 7d
    ports:
      - "5000:5000"
    volumes:
      - ./server/src:/app/src
      - /app/node_modules
    command: npm run dev

  # Frontend (optional, для полной контейнеризации)
  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   container_name: fitness_client
  #   restart: unless-stopped
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./client/src:/app/src
  #     - /app/node_modules
  #   command: npm run dev

volumes:
  postgres_data:
    driver: local